### ISSUE TITLE
Cash previously held and already collected still displaying in subsequent maintenance session.

### ISSUE THREAD

**Issue by khunshwephyo** [maurzcitrus/vmcs#1]
Upon a subsequent re-login to the Maintenance Panel in the same session, the cash previously held and already collected, persists in display. This sometimes causes confusion to Maintainer.

**Comment by kartisuri** [comment]
@cmanian91 (Developer)  This seems to be a valid bug. Please fix it asap!

**Comment by cmanian91** [comment]
@kartisuri (Team Lead) Bug for cash collection display reset has been fixed. please verify

**Comment by kartisuri** [comment]
@Jayendraz (QA) Please do a integration test and let me know the result

**Comment by Jayendraz** [comment]
@kartisuri (TL) Code has been tested and working fine. You may close the issue.

**Comment by kartisuri** [comment]
@khunshwephyo (PM) This issue has been fixed, merged to master and tagged as R1.0.8.1. You may close this issue.

**Comment by khunshwephyo** [comment]
Reviewed the pull request history.  Looks good.  Closing this bug.

**Comment by khunshwephyo** [comment]
Test as User Representative.  Tested Okay. Closing after testing.
