### ISSUE TITLE
Provide an at-a-glance display of the cash amount available.

### ISSUE THREAD

**Issue by khunshwephyo** [maurzcitrus/vmcs#2]
Provide an at-a-glance display of the cash amount available, by denomination, for collection by the Maintainer.  This will enable the Maintainer to readily tally the total cash collected and the total number of coins by denomination displayed in “Show Total Cash Held” and “Press to Collect Cash” when pressed, thus leaving no room for dispute over system errors.

**Comment by kartisuri** [comment]
@Jayendraz (Developer) Please work on the coin related enhancements for display, label and label display.
@cmanian91 (Developer/Analyst) Please work on the maintenance related enhancements for controller and panel.
Karthik (Analyst) Please work on the remaining modules and update the relevant document.

**Comment by kartisuri** [comment]
Karthik (TL) - Document updated and modified TotalCashButtonListener, StoreController files

**Comment by cmanian91** [comment]
@kartisuri (TL)  - Modified Maintenance controller and Maintenance Panel for enhancement

**Comment by Jayendraz** [comment]
@kartisuri (TL) Coin related enhancements for display, label and label display has been done.

**Comment by kartisuri** [comment]
@Jayendraz (QA) Please do a integration test and review the document change and let me know the result

**Comment by Jayendraz** [comment]
@kartisuri (TL) Enhanced code and functionality has been tested and working fine.

**Comment by kartisuri** [comment]
@khunshwephyo (PM) This enhancement added and tested for code and document reviewed. You may close this ticket

**Comment by khunshwephyo** [comment]
As User Representative, I tested this enhancement.  Tested okay.

**Comment by khunshwephyo** [comment]
Closing the issue because all activities have been completed by team members.
